# Generated by Django 3.1.14 on 2022-05-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=11, verbose_name='CEP')),
                ('street', models.CharField(max_length=200, verbose_name='Endereço')),
                ('number', models.CharField(max_length=30, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('cel_phone', models.CharField(max_length=15, verbose_name='Celular')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('cpf', models.IntegerField(verbose_name='Cpf')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Idade')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário')),
                ('date_of_birth', models.DateField(verbose_name='Data de aniversário')),
                ('expertise', models.CharField(choices=[('BOOKS', 'Livros'), ('ARTICLES', 'Artigos'), ('MAGAZINES', 'Revistas'), ('MANGAS', 'Mangas'), ('FILMS', 'Filmes')], max_length=100, verbose_name='Especialidade')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
    ]
