# Generated by Django 3.1.14 on 2022-05-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(default='', max_length=30, verbose_name='Sobrenome')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='E-mail')),
                ('password', models.CharField(default='', max_length=100, verbose_name='Senha')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Telefone')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Idade')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário')),
                ('date_of_birth', models.DateField(default='', verbose_name='Data de aniversário')),
                ('expertise', models.CharField(choices=[('BOOKS', 'Livros'), ('ARTICLES', 'Artigos'), ('MAGAZINES', 'Revistas'), ('MANGAS', 'Mangas'), ('FILMS', 'Filmes')], default='', max_length=100, verbose_name='Especialidade')),
                ('cpf', models.IntegerField(default=0, verbose_name='Cpf')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('description', models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='Descrição')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Anexo')),
            ],
        ),
    ]
